### ISSUE TITLE
taiga-events WebSocket errors

### ISSUE THREAD

**Issue by maxep** [benhutchins/docker-taiga#34]
Hi @benhutchins ,

Thank you very much for this image.

I'm having troubles with taiga-event. I'm using taiga behind a reverse proxy and I keep receiving `WebSocket` errors:
```
WebSocket connection to 'wss://taiga.hulab.co/events' failed: Error during WebSocket handshake: Unexpected response code: 200
WebSocket error: [object Event]
WebSocket connection to 'wss://taiga.hulab.co/events' failed: WebSocket is closed before the connection is established.
```

Here my `docker-compose.yml` : 
```yml
version: '3'

services:

  taiga:
    build: .
    container_name: taiga
    ports:
      - 1000:80
    depends_on:
      - taiga-db
      - taiga-events
      - taiga-rabbit
      - taiga-redis
    links:
      - taiga-db:postgres
      - taiga-rabbit:rabbit
      - taiga-redis:redis
      - taiga-events:events
    environment:
      TAIGA_HOSTNAME: taiga.hulab.co
      TAIGA_DB_HOST: postgres
      TAIGA_DB_NAME: xxx
      TAIGA_DB_USER: xxx
      TAIGA_DB_PASSWORD: xxx
      TAIGA_SSL_BY_REVERSE_PROXY: 'True'
      VIRTUAL_HOST: taiga.hulab.co
      LETSENCRYPT_HOST: taiga.hulab.co
      LETSENCRYPT_EMAIL: xxx
    volumes:
      - ./media:/usr/src/taiga-back/media
      - ./conf:/taiga

  taiga-db:
    image: postgres
    container_name: taiga-db
    environment:
      POSTGRES_DB: xxx
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: xxx
    ports:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data

  taiga-rabbit:
    image: rabbitmq:3
    container_name: taiga-rabbit
    hostname: rabbit

  taiga-redis:
    image: redis:3
    container_name: taiga-redis

  taiga-celery:
    image: celery
    container_name: taiga-celery
    links:
      - taiga-rabbit:rabbit

  taiga-events:
    image: benhutchins/taiga-events
    container_name: taiga-events
    links:
      - taiga-rabbit:rabbit

networks:
  default:
    external:
      name: proxy
```

Any idea how to fix this?

Thanks a lot
