### ISSUE TITLE
How to activate ssl with different port?

### ISSUE THREAD

**Issue by Fabianski-tr** [benhutchins/docker-taiga#80]
Hi,

I have another container using with the 443 server's port, It's possible to run the taiga's container with 8443 server's port with ssl (https)?

I'm using this config:

```yaml
services:
  taiga:
    build: .
    ports:
      - 8080:80
      - 8443:443 # To enable SSL, uncomment this line
    depends_on:
      - postgres
    volumes:
      - ./media:/usr/src/taiga-back/media
      - ./conf/taiga:/taiga
      - ./cert/ssl.crt:/etc/nginx/ssl/ssl.crt:ro # To enable SSL, uncomment this line
      - ./cert/ssl.key:/etc/nginx/ssl/ssl.key:ro # To enable SSL, uncomment this line
    environment:
      TAIGA_HOSTNAME: servername:8443
      TAIGA_DB_NAME: taigadb
      TAIGA_DB_HOST: postgres
      TAIGA_DB_USER: postgres
      TAIGA_DB_PASSWORD: password
      TAIGA_SLEEP: 15 # when the db comes up from docker, it is usually too quick

      TAIGA_SSL: 'True' # To enable SSL, uncomment this line
      # TAIGA_SSL_BY_REVERSE_PROXY: True # To enable SSL, handling by a reverse proxy, uncomment this
```
